spring:
  profiles:
    active: dev

server:
  port: 9000
#  port: 8081

keycloak:
  url: http://localhost:8080
  realm: test

management:
  metrics:
    tags:
      application: movies-backend

my:
  message: dev-message
